name: Sync from GitLab and Create Pull Request

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to sync from GitLab'
        required: true
        default: 'main'
  schedule:
    - cron: '0 12 * * *'  # Runs every day at 12:00 UTC

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      # Step 1: Checkout GitHub repository
      - name: Checkout GitHub repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Required to pull all history and branches
          token: ${{ secrets.GITHUB_TOKEN }}

      # Step 2: Set Git identity
      - name: Set git identity
        run: |-
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      # Step 3: Setup SSH
      - name: Setup SSH
        run: |-
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa git.mtapi.io >> ~/.ssh/known_hosts
      - name: Test SSH Connection
        run: |
          ssh -T git@git.mtapi.io
      # Step 4: Sync from GitLab
      - id: find_mutations
        name: Find mutations
        run: |-
          mkdir -p gitlab-repo
          cd gitlab-repo
          git init
          git remote add origin git@git.mtapi.io:root/mt5-java-api.git
          git fetch origin
          git pull origin main
          ls
          rm -rf .git
          rm -rf .github
          rm -rf META-INF
          rm -rf .gitlab-ci.yml
          rm -rf README.md
          rm pg.txt
          cd ..  # Navigate back to the root directory
