name: Sync from GitLab and Create Pull Request

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to sync from GitLab'
        required: true
        default: 'master'
  schedule:
    - cron: '0 12 * * *'  # Runs every day at 12:00 UTC

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      # Step 1: Checkout GitHub repository
      - name: Checkout GitHub repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Required to pull all history and branches
          token: ${{ secrets.GITHUB_TOKEN }}

      # Step 2: Set Git identity
      - name: Set git identity
        run: |-
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      # Step 3: Pull code from GitLab repository and check for changes
      - id: find_mutations
        name: Find mutations
        run: |-
          mkdir -p gitlab-repo
          cd gitlab-repo
          git init
          git remote add origin https://oauth2:${{ secrets.GITLAB_SYNC_TOKEN }}@git.mtapi.io/root/mt5-java-api.git
          git fetch origin
          git pull origin master
          ls
          rm -rf .git
          rm -rf .github
          rm -rf META-INF
          rm -rf .gitlab-ci.yml
          rm -rf README.md
          rm pg.txt
          cd ..  # Navigate back to the root directory
