name: Docker Build and Push

on:
  push:
    branches:
      - merge-workflow  # Change this to your default branch if necessary

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2


      - name: Build and Tag Docker image
        id: build-image
        run: |
          SHORT_SHA="${GITHUB_SHA}"
          IMAGE_NAME=my-image
          docker build -t ${IMAGE_NAME}:${FULL_SHA} .


