name: Sync from GitLab and Create Pull Request

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to sync from GitLab'
        required: true
        default: 'main'
  schedule:
    - cron: '0 12 * * *'  # Runs every day at 12:00 UTC

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      # Step 1: Checkout GitHub repository
      - name: Checkout GitHub repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Required to pull all history and branches
          token: ${{ secrets.GITHUB_TOKEN }}

      # Step 2: Set Git identity
      - name: Set git identity
        run: |-
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git config --global credential.helper store
          echo "https://${{ secrets.GITLAB_USERNAME }}:${{ secrets.GITLAB_PASSWORD }}@git.mtapi.io/root/mt5-java-api.git" > ~/.git-credentials
      - id: find_mutations
        name: Find mutations
        run: |-
          mkdir -p gitlab-repo
          cd gitlab-repo
          git init
          git remote add origin https://git.mtapi.io/root/mt5-java-api.git
          git fetch origin 
          git pull origin main
        env:
          GIT_USERNAME: ${{ secrets.GITLAB_USERNAME }}
          GIT_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
